require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BillingsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Billing. As you add validations to Billing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BillingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all billings as @billings" do
      billing = Billing.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:billings)).to eq([billing])
    end
  end

  describe "GET #show" do
    it "assigns the requested billing as @billing" do
      billing = Billing.create! valid_attributes
      get :show, {:id => billing.to_param}, valid_session
      expect(assigns(:billing)).to eq(billing)
    end
  end

  describe "GET #new" do
    it "assigns a new billing as @billing" do
      get :new, {}, valid_session
      expect(assigns(:billing)).to be_a_new(Billing)
    end
  end

  describe "GET #edit" do
    it "assigns the requested billing as @billing" do
      billing = Billing.create! valid_attributes
      get :edit, {:id => billing.to_param}, valid_session
      expect(assigns(:billing)).to eq(billing)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Billing" do
        expect {
          post :create, {:billing => valid_attributes}, valid_session
        }.to change(Billing, :count).by(1)
      end

      it "assigns a newly created billing as @billing" do
        post :create, {:billing => valid_attributes}, valid_session
        expect(assigns(:billing)).to be_a(Billing)
        expect(assigns(:billing)).to be_persisted
      end

      it "redirects to the created billing" do
        post :create, {:billing => valid_attributes}, valid_session
        expect(response).to redirect_to(Billing.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved billing as @billing" do
        post :create, {:billing => invalid_attributes}, valid_session
        expect(assigns(:billing)).to be_a_new(Billing)
      end

      it "re-renders the 'new' template" do
        post :create, {:billing => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested billing" do
        billing = Billing.create! valid_attributes
        put :update, {:id => billing.to_param, :billing => new_attributes}, valid_session
        billing.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested billing as @billing" do
        billing = Billing.create! valid_attributes
        put :update, {:id => billing.to_param, :billing => valid_attributes}, valid_session
        expect(assigns(:billing)).to eq(billing)
      end

      it "redirects to the billing" do
        billing = Billing.create! valid_attributes
        put :update, {:id => billing.to_param, :billing => valid_attributes}, valid_session
        expect(response).to redirect_to(billing)
      end
    end

    context "with invalid params" do
      it "assigns the billing as @billing" do
        billing = Billing.create! valid_attributes
        put :update, {:id => billing.to_param, :billing => invalid_attributes}, valid_session
        expect(assigns(:billing)).to eq(billing)
      end

      it "re-renders the 'edit' template" do
        billing = Billing.create! valid_attributes
        put :update, {:id => billing.to_param, :billing => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested billing" do
      billing = Billing.create! valid_attributes
      expect {
        delete :destroy, {:id => billing.to_param}, valid_session
      }.to change(Billing, :count).by(-1)
    end

    it "redirects to the billings list" do
      billing = Billing.create! valid_attributes
      delete :destroy, {:id => billing.to_param}, valid_session
      expect(response).to redirect_to(billings_url)
    end
  end

end
